### ISSUE TITLE
Should "Build System Integration" says `assetDir` instead of `assets` in the example?

### ISSUE THREAD

**Issue by daj** [robolectric/robolectric.github.io#121]
The [Build System Integration](https://github.com/robolectric/robolectric.github.io/blob/master/build-system-integration.md) shows example usage of `@Config`:

> or `@Config(manifest="...", res="...", assets="...")` in your tests

Based on other examples I have seen, should this say `assetDir` ([docs](http://robolectric.org/javadoc/latest/org/robolectric/annotation/Config.html#assetDir())) instead of `assets`?

The `assetDir` option is deprecated, but these docs did briefly confuse me when I was searching online for definitive information about this option.

**Comment by utzcoz** [comment]
@daj Good catch. From the doc, it is `assetDir`. Could you help to send a PR for it? Thanks.

**Comment by daj** [comment]
@utzcoz done: https://github.com/robolectric/robolectric.github.io/pull/123

**Comment by utzcoz** [comment]
Fixed by  https://github.com/robolectric/robolectric.github.io/pull/123.
