### ISSUE TITLE
javadoc for @Config missing?

### ISSUE THREAD

**Issue by ened** [robolectric/robolectric.github.io#15]
It might be better to reactivate that Javadoc link as other websites also link to it.

http://robolectric.org/javadoc/org/robolectric/annotation/Config.html

**Comment by jaredsburrows** [comment]
It is located here: http://robolectric.org/configuring/

@ened @erd Can we close this?

**Comment by erd** [comment]
This issue is referring to the javadoc (which is missing), not the configuring guide you linked to.

**Comment by erd** [comment]
The Javadocs for 3.0 should now include the docs for `Config`.
