### ISSUE TITLE
Robolectric with Android Studio 1.1.0 

### ISSUE THREAD

**Issue by guitcastro** [robolectric/robolectric.github.io#17]
I tried to use Robolectric with the new Android Studio 1.1. Running tests using command line work fine but for the IDE Integration work we had to follow the items 3, 4 and 5 of this guide: http://tools.android.com/tech-docs/unit-testing-support.

So I think it´s a good idea to update the documentation.

**Comment by erd** [comment]
The main "Getting Started" page now has instructions on how to set-up Robolectric with Gradle and Android Studio (done as part of #18).
