### ISSUE TITLE
Restore custom CSS/assets for Javadoc

### ISSUE THREAD

**Issue by MGaetan89** [robolectric/robolectric.github.io#276]
## Context

While working on migrating Robolectric's `buildSrc` folder to Kotlin, I stumbled upon this line:
https://github.com/robolectric/robolectric/blob/0156803c11ed2109ac53b0c5843d9b7cb7c6ecd1/buildSrc/src/main/groovy/org/robolectric/gradle/DeployedRoboJavaModulePlugin.groovy#L28

However, since the [new website](https://github.com/robolectric/robolectric.github.io/pull/212), this file does not exist anymore:
<img width="410" alt="Screenshot 2024-07-17 at 10 29 45" src="https://github.com/user-attachments/assets/d6f20663-d8f8-4987-aca9-d1cb3d33b553">

## Tasks

The goal of this ticket is to restore these files and all their related resources.

Known missing files:
- [ ] https://robolectric.org/assets/css/main.css → https://github.com/robolectric/robolectric/pull/9515
- [x] http://robolectric.org/images/logo-with-bubbles-down.png → https://github.com/robolectric/robolectric.github.io/pull/281

**Comment by MGaetan89** [comment]
I'm starting to wonder if adding back the `main.css` file makes sense. From what I can see, it's only third party CSS (from the legacy HTML5 Up website), and nothing specific to Robolectric. Maybe it's better to just keep the default Javadoc stylesheet.
It doesn't seem to be included in the online Javadoc (for example, there's no reference to it in 4.13: `view-source:https://robolectric.org/javadoc/4.13/`), but only in the generated Javadoc jar.
Also, adding that file back means adding all the related files back as well (FontAwesome CSS, various fonts files, maybe some images).

@utzcoz @brettchabot @hoisie what do you think about dropping that file for good, and removing its reference for good?
https://github.com/robolectric/robolectric/blob/3911f5f9568696ab0dc72544185f089d98b5ae87/buildSrc/src/main/java/org/robolectric/gradle/DeployedRoboJavaModulePlugin.kt#L65-L69

**Comment by hoisie** [comment]
👍 for removing it. Seems obsolete now.

**Comment by MGaetan89** [comment]
> 👍 for removing it. Seems obsolete now.

I've submitted a PR to remove the link to `main.css`: https://github.com/robolectric/robolectric/pull/9515
