### ISSUE TITLE
Typo in contributor guidelines

### ISSUE THREAD

**Issue by Jesse-Weinstein-Zonar** [robolectric/robolectric.github.io#33]
See comment here: https://github.com/robolectric/robolectric.github.io/commit/0b359bb413ff3ccb9d818adfd57d4b70b8781f9a#commitcomment-19729316

**Comment by ngbravo** [comment]
Not really a typo. The instruction above says to fork and then clone, so username/robolectric is correct. @jongerrish close?

**Comment by Jesse-Weinstein-Zonar** [comment]
OK, then the typo is the imbalance between mentioning one step in a single word: "fork", and the other step with an entire copy-able command. I'll change the PR to take out the misleading command, then.

**Comment by utzcoz** [comment]
Hi @Jesse-Weinstein-Zonar, I agree with @ngbravo said at https://github.com/robolectric/robolectric.github.io/issues/33#issuecomment-349350166, username/robolectric is fine after the instruction recommends contributor to fork project firstly. I will close it, feel free to reopen it if you have any problem. Thanks.
