### ISSUE TITLE
Other Environment: Fix href to point to prod env

### ISSUE THREAD

**Issue by Labelpm** [robolectric/robolectric.github.io#65]
### Description
Just surfed through the site and encountered small issue for two href blocks, they are heading to localhost env instead of prod

### Steps to Reproduce
1. http://robolectric.org/getting-started/
2. Scroll to Other Environment
3. Verify
3.1 Older Android Studio/Gradle Versions
3.2 Maven & Eclipse

### Actual behavior
Older Android Studio/Gradle Versions -> http://127.0.0.1:4000/other-environments/#android-studio--gradle-agp--30
Maven & Eclipse -> http://127.0.0.1:4000/other-environments/#maven--eclipse

### Expected behavior
Older Android Studio/Gradle Versions -> http://robolectric.org/other-environments/#android-studio--gradle-agp--30
Maven & Eclipse -> http://robolectric.org/other-environments/#maven--eclipse

**Comment by xian** [comment]
Fixed, thanks!
