### ISSUE TITLE
Change set up of test app with Dagger instead of RoboGuice

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric.github.io#74]
Since RoboGuice is retired, perhaps give an example to use Dagger 2?

Also, would love a bit of help with structuring app with Dagger 2 to aid in replacing components in tests (out of scope for issue but pointers would help).

Relevant page: http://robolectric.org/custom-test-runner/

**Comment by utzcoz** [comment]
Maybe we should add link to integrate Robolectric with Hilt. There is an official documentation: https://dagger.dev/hilt/robolectric-testing.html.
