### ISSUE TITLE
Robolectric 4.6's javadoc has many broken links

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric.github.io#90]
See https://github.com/robolectric/robolectric.github.io/pull/89#issuecomment-928099034 and its related discussion.

**Comment by hoisie** [comment]
Another option may be to just use JDK11 and then manually edit some JS logic to fix the issue. I saw that solution being mentioned.

**Comment by utzcoz** [comment]
JDK 14's error looks like related to network. It shown it can't fetch URl `developer.android.com`. I will try proxy to check this problem.

**Comment by utzcoz** [comment]
@hoisie I used following patch to fix those problem:

```
@@ -89,6 +89,13 @@ gradle.projectsEvaluated {
                         "https://docs.oracle.com/javase/8/docs/api/",
                         "https://developer.android.com/reference/",
                 ]
+                source("8")
+                jFlags(
+                    '-Dhttp.proxyHost=' + System.properties['http.proxyHost'],
+                    '-Dhttp.proxyPort=' + System.properties['http.proxyPort'],
+                    '-Dhttps.proxyHost=' + System.properties['https.proxyHost'],
+                    '-Dhttps.proxyPort=' + System.properties['https.proxyPort']
+                )
                 header = headerHtml
                 footer = headerHtml
```

1. Use `jFlags` to pass proxy to javadocs for `developer.android.com` accessing.
2. Set ` source("8")` for javadocs to avoid generating failed with unamed module problem, likes this https://issues.apache.org/jira/browse/MJAVADOC-583. 

What about adding a javadocs generating task to valid javadocs aggregating for high JDK version at GitHub Action? I think the second part can be sent with a PR.
